[package]
name = "utcp"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.8.0"
crossbeam-skiplist = "0.1.3"
env_logger = { version="0.11.6", features=["color"] }
libc = "0.2.169"
log = "0.4.25"
signal-hook = "0.3.17"
thiserror = "2.0.11"
